spring:
  application:
    name: sms-api

  mail:
    host: smtp.gmail.com
    port: 587
    username: pankajdhami811@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

twilio:
  account-sid: 
  auth-token: 
  from-number: 
